### ISSUE TITLE
Read Attached File and Share Feedback!

### ISSUE THREAD

**Issue by Huzaifa2420** [Huzaifa2420/AMS#5]
[CustomerList.pdf](https://github.com/Huzaifa2420/AMS/files/8560282/CustomerList.pdf)

**Comment by SaadMahmoodAhmad** [comment]
Hello

**Comment by Huzaifa2420** [comment]
Is the File Ok??
If yes, then reply me back so that i can close the issue or you can close it at your end...

**Comment by Huzaifa2420** [comment]
Closing the issue as the Pull Request against that issue has been merged.
